-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE DOADOR (
ID_DOADOR INTEGER PRIMARY KEY,
NOME VARCHAR(45),
EMAIL VARCHAR(45),
NASCIMENTO DATETIME,
GENERO VARCHAR(45),
RG VARCHAR(15),
CPF VARCHAR(15),
TELEFONE VARCHAR(15),
TELEFONE1 VARCHAR(15),
RUA VARCHAR(45),
BAIRRO VARCHAR(45),
NUMERO VARCHAR(15),
COMPLEMENTO VARCHAR(15),
CEP VARCHAR(15),
CIDADE VARCHAR(45),
POSTO_PARA_DOACAO VARCHAR(10),
DATA_PARA_DOACAO DATETIME,
TIPO_SANGUINEO VARCHAR(10)
)

CREATE TABLE VINICIUS AFONSO OLIVEIRA (

)

