-- MySQL Script generated by MySQL Workbench
-- Tue Jan  2 19:32:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sangue_e_vida
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sangue_e_vida
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sangue_e_vida` DEFAULT CHARACTER SET utf8 ;
USE `sangue_e_vida` ;

-- -----------------------------------------------------
-- Table `sangue_e_vida`.`DOADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sangue_e_vida`.`DOADOR` (
  `ID_DOADOR` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci' NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `NASCIMENTO` DATE NOT NULL,
  `GENERO` VARCHAR(45) NOT NULL,
  `RG` VARCHAR(15) NOT NULL,
  `CPF` VARCHAR(15) NOT NULL,
  `TELEFONE` VARCHAR(15) NOT NULL,
  `CELULAR` VARCHAR(15) NOT NULL,
  `RUA` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci' NOT NULL,
  `BAIRRO` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci' NOT NULL,
  `NUMERO` VARCHAR(15) NOT NULL,
  `COMPLEMENTO` VARCHAR(10) CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci' NULL,
  `CEP` VARCHAR(15) NOT NULL,
  `CIDADE` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci' NOT NULL,
  `POSTODOACAO` VARCHAR(45) CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci' NOT NULL,
  `DATA` DATE NOT NULL,
  `TIPOSANGUE` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID_DOADOR`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


use sangue_e_vida;
select * from doador;